feat: use fettle config by default
fidildev/fettle pull request #43
Opened 2023-03-12 06:22 UTC by tylerkron

- Uses fettle config for github creds.
- Will create fettle config if one doesn't exist
- Checks for 600 permission on fettle config
- Falls back to environment variables if fettle config doesn't contain github creds

Used chatGPT to make @mikeylive

2023-03-12 06:29 UTC, milehimikey requested changes

2023-03-12 06:29 UTC, milehimikey commented on src/main/kotlin/dev/fidil/fettle/FettleApplication.kt
> +            exitProcess(1)
Not sure this should end the app, maybe just a warning

2023-03-12 06:29 UTC, milehimikey commented on src/main/kotlin/dev/fidil/fettle/FettleApplication.kt
> +    if (!GitHubConfig.configFile.exists()) {
Why create the file? I think just checking for it's existence is fine here, if we want a command that can create a config file that's different

2023-03-12 06:29 UTC, milehimikey commented on src/main/kotlin/dev/fidil/fettle/FettleApplication.kt
> +            exitProcess(1)
Shouldn't exit the app

2023-03-12 07:16 UTC, mikeylive submitted a review, later dismissed

2023-03-12 09:50 UTC, JacobBrauchler submitted a review, later dismissed

2023-03-13 01:27 UTC, JacobBrauchler approved these changes

2023-03-13 01:31 UTC, merged