feat: #24 add dependabot configuration
fidildev/fettle pull request #44
Opened 2023-03-13 21:48 UTC by vrkljam

2023-03-13 23:45 UTC, milehimikey requested changes

2023-03-13 23:45 UTC, milehimikey commented on build.gradle
> +buildscript{
Don't need this file.

2023-03-13 23:45 UTC, milehimikey commented on dependencies.gradle
> +ext {
Nor this one.

2023-03-14 02:58 UTC, tylerkron requested changes

2023-03-14 02:58 UTC, tylerkron commented on .github/dependabot.yml
> +      - "deps:"
we'll want a space after the colon `"deps: `

2023-03-14 15:39 UTC, mikeylive commented on .github/dependabot.yml
> +version:1
You need a space after the colon (:) here. And this should probably be `version: 2`

2023-03-14 16:06 UTC, tkronpax8 approved these changes

2023-03-14 16:09 UTC, tylerkron approved these changes

2023-03-15 02:56 UTC, JacobBrauchler approved these changes

2023-03-15 02:57 UTC, merged