feat: 30 run all fettle functions at once
fidildev/fettle pull request #55
Opened 2023-03-22 00:39 UTC by mikeylive

2023-03-22 02:21 UTC, tylerkron requested changes
A couple of comments

1. I get a handful of lint issues building this
<img width="1571" alt="image" src="https://user-images.githubusercontent.com/6320493/226785176-c1a6411e-f174-42e8-8b85-29d3aba7ded7.png">

2. Can you update the readme of how to run all the fettle functions?

2023-03-23 02:27 UTC, mikeylive commented
Lint issues, did we investigate this? https://kotlinlang.org/docs/code-style-migration-guide.html  Not sure this is the right approach but I'll fix.

2023-03-23 02:29 UTC, JacobBrauchler commented
> Lint issues, did we investigate this? https://kotlinlang.org/docs/code-style-migration-guide.html Not sure this is the right approach but I'll fix.

we are using ktlint if you look at the readme it will tell you the command to run to give us a precommit hook. then ktlint format runs every time. But no I didn't look at that.

2023-03-23 02:55 UTC, mikeylive commented
Fixed...thanks for both being shitty reviewers so I can't mark things as out of date or resolved 🖕

2023-03-23 02:58 UTC, JacobBrauchler commented
> Fixed...thanks for both being shitty reviewers so I can't mark things as out of date or resolved 🖕

I just replied I will dismiss as soon as I say its good 🖕

2023-03-23 03:11 UTC, JacobBrauchler commented on src/main/kotlin/dev/fidil/fettle/handler/GitHubFettleHandler.kt
> +            CommandResult.Passed("PASS")
some say PASS and FAIL and some say PASSED and FAILED make it consistent and make a constant for fucks sake

2023-03-23 03:13 UTC, mikeylive commented on src/main/kotlin/dev/fidil/fettle/handler/GitHubFettleHandler.kt
> +            CommandResult.Passed("PASS")
It doesn't matter...yet. The only thing that matters to score is whether its CommandResult.Passed or CommandResult.Failed....the string within it is for later use when surely Shirly someone will want to know why it passed or failed.

2023-03-23 03:16 UTC, mikeylive commented on src/main/kotlin/dev/fidil/fettle/handler/GitHubFettleHandler.kt
> +            CommandResult.Passed("PASS")
Fixed.

2023-03-23 03:17 UTC, JacobBrauchler requested changes

2023-03-23 03:17 UTC, JacobBrauchler commented on src/main/kotlin/dev/fidil/fettle/handler/GitHubFettleHandler.kt
> +            CommandResult.Passed("")
???? 🖕

2023-03-23 03:19 UTC, JacobBrauchler commented on src/main/kotlin/dev/fidil/fettle/handler/GitHubFettleHandler.kt
> +            CommandResult.Passed("")
lets just make two constants and use them throughout the class 🖕

2023-03-23 03:20 UTC, mikeylive commented on src/main/kotlin/dev/fidil/fettle/handler/GitHubFettleHandler.kt
> +            CommandResult.Passed("")
replace didn't find the blanks....your fault 🖕

2023-03-23 03:21 UTC, JacobBrauchler approved these changes

2023-03-23 03:22 UTC, merged